### PR TITLE
fix statistics with GooseTask name

### LINKED ISSUE #161: invalid statstics in 0.10
In preparing for a `0.10` release, while updating statistics in built-in documentation, I'm noticing a discrepancy that needs to be analyzed and either explained or fixed before the release:

```
 === PER TASK METRICS ===
 ------------------------------------------------------------------------------
 Name                     |   # times run |        # fails |   task/s |  fail/s
 ------------------------------------------------------------------------------
 1: LoadtestTasks         |
   1:                     |            44 |         0 (0%) |     2.93 |    0.00
   2: bar                 |            13 |         0 (0%) |     0.87 |    0.00
 -------------------------+---------------+----------------+----------+--------
 Aggregated               |            57 |         0 (0%) |     3.80 |    0.00
 ------------------------------------------------------------------------------
 Name                     |    Avg (ms) |        Min |         Max |     Median
 ------------------------------------------------------------------------------
 1: LoadtestTasks         |
   1:                     |        8.34 |          6 |          11 |          8
   2: bar                 |        7.92 |          6 |          12 |          7
 -------------------------+-------------+------------+-------------+-----------
 Aggregated               |        8.25 |          6 |          12 |          8

 === PER REQUEST METRICS ===
 ------------------------------------------------------------------------------
 Name                     |        # reqs |        # fails |    req/s |  fail/s
 ------------------------------------------------------------------------------
 GET /                    |            17 |         0 (0%) |     1.13 |    0.00
 GET bar                  |            40 |         0 (0%) |     2.67 |    0.00
 -------------------------+---------------+----------------+----------+--------
 Aggregated               |            57 |         0 (0%) |     3.80 |    0.00
 ------------------------------------------------------------------------------
 Name                     |    Avg (ms) |        Min |        Max |      Median
 ------------------------------------------------------------------------------
 GET /                    |        8.65 |          6 |          11 |          9
 GET bar                  |        8.07 |          6 |          12 |          8
 -------------------------+-------------+------------+-------------+-----------
 Aggregated               |        8.25 |          6 |          12 |          8

07:32:39 [ INFO] stopping after 30 seconds...
```

These numbers were generated running the example from the documentation:

```rust
use goose::prelude::*;

fn main() -> Result<(), GooseError> {
    let _goose_metrics = GooseAttack::initialize()?
        .register_taskset(taskset!("LoadtestTasks")
            .set_wait_time(0, 3)?
            // Register the foo task, assigning it a weight of 10.
            .register_task(task!(loadtest_foo).set_weight(10)?)
            // Register the bar task, assigning it a weight of 2 (so it
            // runs 1/5 as often as bar). Apply a task name which shows up
            // in metrics.
            .register_task(task!(loadtest_bar).set_name("bar").set_weight(2)?)
        )
        // You could also set a default host here, for example:
        //.set_default(GooseDefault::Host, "http://dev.local/")
        .execute()?;

    Ok(())
}

// A task function that loads `/path/to/foo`.
async fn loadtest_foo(user: &GooseUser) -> GooseTaskResult {
    let _goose = user.get("/path/to/foo").await?;

    Ok(())
}   

// A task function that loads `/path/to/bar`.
async fn loadtest_bar(user: &GooseUser) -> GooseTaskResult {
    let _goose = user.get("/path/to/bar").await?;

    Ok(())
}   
```

I was expected we should be running `foo` more than `bar`, and per-task statistics should agree with per-request statistics. Needs review.

### PR DESCRIPTION
**Pull request by jeremyandrews**
The `GooseUser` object didn't have direct access to the `GooseTask` name if set. The old implementation was essentially caching the last seem task name, but this wasn't working correctly. Instead I've re-worked the logic so we pass the actual `GooseTask` name to the `GooseUser` when building a weighted list of tasks for the user.

Now statistics are being generated exactly as expected, and the documentation can be properly updated for the [0.10.0 release](https://github.com/tag1consulting/goose/pull/160). Fixes #161 

Running the example load test generates the following statistics, and all the numbers now match up correctly as expected:

```
 === PER TASK METRICS ===
 ------------------------------------------------------------------------------
 Name                     |   # times run |        # fails |   task/s |  fail/s
 ------------------------------------------------------------------------------
 1: LoadtestTasks         |
   1:                     |         9,231 |         0 (0%) |   307.70 |    0.00
   2: bar                 |         1,843 |         0 (0%) |    61.43 |    0.00
 -------------------------+---------------+----------------+----------+--------
 Aggregated               |        11,074 |         0 (0%) |   369.13 |    0.00
 ------------------------------------------------------------------------------
 Name                     |    Avg (ms) |        Min |         Max |     Median
 ------------------------------------------------------------------------------
 1: LoadtestTasks         |
   1:                     |       21.37 |          6 |         152 |         18
   2: bar                 |       21.28 |          9 |         152 |         18
 -------------------------+-------------+------------+-------------+-----------
 Aggregated               |       21.36 |          6 |         152 |         18

 === PER REQUEST METRICS ===
 ------------------------------------------------------------------------------
 Name                     |        # reqs |        # fails |    req/s |  fail/s
 ------------------------------------------------------------------------------
 GET /path/to/foo         |         9,231 |         0 (0%) |   307.70 |    0.00
 GET bar                  |         1,843 |         0 (0%) |    61.43 |    0.00
 -------------------------+---------------+----------------+----------+--------
 Aggregated               |        11,074 |         0 (0%) |   369.13 |    0.00
 ------------------------------------------------------------------------------
 Name                     |    Avg (ms) |        Min |        Max |      Median
 ------------------------------------------------------------------------------
 GET /path/to/foo         |       21.33 |          6 |         152 |         18
 GET bar                  |       21.23 |          9 |         152 |         18
 -------------------------+-------------+------------+-------------+-----------
 Aggregated               |       21.31 |          6 |         152 |         18
 ------------------------------------------------------------------------------
 Slowest page load within specified percentile of requests (in ms):
 ------------------------------------------------------------------------------
 Name                     |    50% |    75% |    98% |    99% |  99.9% | 99.99%
 ------------------------------------------------------------------------------
 GET /path/to/foo         |     18 |     21 |     69 |     73 |    140 |    140
 GET bar                  |     18 |     21 |     69 |     73 |    150 |    150
 -------------------------+--------+--------+--------+--------+--------+-------
 Aggregated               |     18 |     21 |     69 |     73 |    150 |    150
```

### CODE REVIEW

File: src/goose.rs [hunk 1]
```diff
@@ -965,8 +961,6 @@ impl GooseUser {
             weighted_on_start_tasks: Vec::new(),
             weighted_tasks: Vec::new(),
             weighted_on_stop_tasks: Vec::new(),
-            task_request_name: None,
-            request_name: None,
```
Comment (jeremyandrews) [inline src/goose.rs:969]: Oddly `request_name` wasn't even used. And `task_request_name` wasn't consistently working correctly as the required information wasn't directly available to the `GooseUser`. Instead we expand the `WeightedGooseTasks` type to include the GooseTask name, if set.

File: src/lib.rs [hunk 2]
```diff
@@ -356,7 +356,7 @@ lazy_static! {
 }
 
 /// Internal representation of a weighted task list.
-type WeightedGooseTasks = Vec<Vec<usize>>;
+type WeightedGooseTasks = Vec<Vec<(usize, String)>>;
```
Comment (jeremyandrews) [inline src/lib.rs:359]: This is the main change in this PR, expanding `WeightedGooseTasks` to also include a the GooseTask name, if set.

File: src/user.rs [hunk 3]
```diff
@@ -200,14 +189,14 @@ pub async fn user_main(
 async fn invoke_task_function(
     function: &GooseTaskFunction,
     thread_user: &GooseUser,
-    task_index: usize,
+    thread_task_index: usize,
```
Comment (jeremyandrews) [inline src/user.rs:192]: Though not strictly required, it was odd how all other variables were prefixed with `thread_` -- this change improves the readability of the code affected by these changes.

**Review by LionsAd — APPROVED** [review]
RTBM
